import Head from 'next/head'
import { useRef } from 'react'
import { useReactToPrint } from 'react-to-print'
import { ResumeBuild } from '@components/ResumeBuild'
import { ResumePreview } from '@components/ResumePreview'
import { Button, Stack } from '@chakra-ui/react'
import { MdOutlineFileDownload } from 'react-icons/md'

export default function Home() {

  const componentRef = useRef(null);
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });

  return (
    <>
      <Head>
        <title>Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <ResumeBuild />
        <Stack alignItems={'flex-end'}>
          <ResumePreview ref={componentRef} />
          <Button rightIcon={<MdOutlineFileDownload />} onClick={handlePrint} colorScheme={'purple'}>Download</Button>
        </Stack>
      </>

    </>
  )
}
