import { TabList, Tabs, Tab, TabPanels, TabPanel, Box, Text, Divider } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Biodata from '../components/Biodata'
import Education from '../components/Education'
import Experience from '../components/Experience'
import PreviewBiodata from '../components/PreviewBiodata'
import PreviewEducation from '../components/PreviewEducation'
import PreviewExperience from '../components/PreviewExperience'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Resume Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
        <Box>
          <Tabs>
            
            <TabList>
              <Tab><Text>Personal Details</Text></Tab>
              <Tab><Text>Education</Text></Tab>
              <Tab><Text>Work Experience</Text></Tab>
              <Tab><Text>Skills</Text></Tab>
            </TabList>
            
            <TabPanels>
              
              <TabPanel>
                <Biodata />
              </TabPanel>
              
              <TabPanel>
                <Education />
              </TabPanel>
              
              <TabPanel>
                <Experience />
              </TabPanel>
            
            </TabPanels>
          
          </Tabs>
        </Box>

        <Box>
          <PreviewBiodata />
          <Divider />
          <PreviewEducation />
          <Divider />
          <PreviewExperience />
        </Box>
      </main>

    </div>
  )
}
