import { useState, ChangeEvent } from 'react'
import { TabList, Tabs, Tab, TabPanels, TabPanel, Box, Text, Divider } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BioData from '../components/biodata'
import Education from '../components/education'
import Experience from '../components/experience'
import DisplayBio from '../components/displayBio'

export default function Home() {

  const [bioData, setBioData] = useState({})
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setBioData({ ...bioData, [name]: value })
    console.log(bioData)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>CV App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box>
          <Tabs>
            <TabList>
              <Tab><Text>Personal Details</Text></Tab>
              <Tab><Text>Education</Text></Tab>
              <Tab><Text>Work Experience</Text></Tab>
              <Tab><Text>Skills</Text></Tab>
            </TabList>
            <TabPanels>
              <TabPanel>
                <BioData handleChange={handleChange} />
              </TabPanel>
              <TabPanel>
                <Education />
              </TabPanel>
              <TabPanel>
                <Experience />
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>

        <Box>
          <DisplayBio bioData={bioData} />
          <Divider />
        </Box>
      </main>

    </div>
  )
}
